server:
  port: 8079
spring:
  application:
    name: ipo-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8000/auth/realms/ipo-realm
  client:
    provider:
      keycloak:
        issuer-uri: http://localhost:8000/auth/realms/ipo-realm
        user-name-attribute: preferred_username
    registration:
      keycloak:
        client-id: ipo
        client-secret: M9f0jrjYwwo9r3BLuMDWt7W2VxZOXHkw
        scope: openid
  globalcors:
    corsConfigurations:
      '[/**]':
        allowedOrigins: "*"
        allowedMethods:
          - GET
          - POST
          - DELETE
        allowedHeaders:
          - "*"

security:
  access:
    path:
      moderator: moderator-access
      admin: admin-access
    role:
      name:
        moderator: Moderator
        admin: Admin


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:5757/eureka

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway